dbSchema: activity

logging:
  level:
    ru.waveaccess.tver.activity: 'INFO'

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    parameters:
      dbSchema: ${dbSchema}
    enabled: true
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate.default_schema: ${dbSchema}
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/${dbSchema}?useSSL=false&allowMultiQueries=true